spring:
  application:
    name: gateway
  profiles:
    active: dev
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1

  cloud:
    gateway:
      routes:
        - id: auth_svc_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth_svc/**
          filters:
            - StripPrefix=2
        - id: movie_svc_route
          uri: http://localhost:8082
          predicates:
            - Path=/api/movie_svc/**
          filters:
            - StripPrefix=2

server:
  port: 8080
